import httpx

with open("text1.txt", 'w') as file:
    print("Proxies Scraper")
    file.write(httpx.get("https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=anonymous").text)
    file.write(httpx.get("https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt").text)
    file.write(httpx.get("https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt").text)
    file.write(httpx.get("https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt").text)
    file.write(httpx.get("https://api.proxyscrape.com/?request=displayproxies&proxytype=socks5").text)
    file.write(httpx.get("https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks5").text)
    file.write(httpx.get("https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5&timeout=10000&country=all&simplified=true").text)
    file.write(httpx.get("https://www.proxyscan.io/download?type=http").text)
    file.write(httpx.get("https://www.proxyscan.io/download?type=https").text)
    file.write(httpx.get("https://raw.githubusercontent.com/mmpx12/proxy-list/master/https.txt").text)
    file.write(httpx.get("https://proxyspace.pro/http.txt").text)
    file.write(httpx.get("https://api.proxyscrape.com/?request=displayproxies&proxytype=http").text)
    file.write(httpx.get("https://www.proxy-list.download/api/v1/get?type=http").text)
    file.write(httpx.get("https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt").text)
    file.write(httpx.get("http://worm.rip/socks4.txt").text)
    file.write(httpx.get("http://worm.rip/socks5.txt").text)
    file.write(httpx.get("http://worm.rip/http.txt").text)
    file.write(httpx.get("https://sheesh.rip/all.txt").text)
    file.write(httpx.get("http://alexa.lr2b.com/proxylist.txt").text)
    file.write(httpx.get("https://www.proxy-list.download/api/v1/get?type=socks4").text)
    file.write(httpx.get("https://www.proxy-list.download/api/v1/get?type=socks5").text)
    file.write(httpx.get("https://www.proxy-list.download/api/v1/get?type=http").text)
    file.write(httpx.get("https://api.openproxylist.xyz/http.txt").text)
    file.write(httpx.get("https://api.openproxylist.xyz/socks4.txt").text)
    file.write(httpx.get("https://api.openproxylist.xyz/socks5.txt").text)
    file.write(httpx.get("http://rootjazz.com/proxies/proxies.txt").text)
    file.write(httpx.get("https://multiproxy.org/txt_all/proxy.txt").text)
    file.write(httpx.get("https://proxy-spider.com/api/proxies.example.txt").text)
    file.write(httpx.get("https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt").text)
    file.write(httpx.get("https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt").text)
    file.write(httpx.get("https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt").text)
    file.write(httpx.get("https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies.txt").text)
    file.write(httpx.get("https://raw.githubusercontent.com/RX4096/proxy-list/main/archive/all.txt").text)
    file.write(httpx.get("https://raw.githubusercontent.com/mertguvencli/http-proxy-list/main/proxy-list/data.txt").text)
    file.write(httpx.get("https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/http.txt").text)
    file.write(httpx.get("https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks4.txt").text)
    file.write(httpx.get("https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks5.txt").text)
    file.write(httpx.get("https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt").text)
    file.write(httpx.get("https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt").text)
    file.write(httpx.get("https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt").text)